//传给后端的数据模型
export const initFormData = {
    Test_Number: "",
    Current_Address_Detail: "",
    Examinee_Type_Code: "",
    Body_Exam_Number: "",
    Name: "",
    Sex: "",
    Grade_Id: "",
    Class_Id: "",
    Id_Number: "",
    Student_Status: "",
    Nation_Code: "",
    Phone: "",
    Current_Address: [],
    Headmaster_Name: "",
    Headmaster_Phone: "",
    Is_Unsuitable_Exercise: "",
    Is_Apply_Exempt_Examination: "FALSE",
    Sf_Ssmz: "FALSE",
    Sf_Gq_Hqzn: "FALSE",
    Sf_Twj: "FALSE",
    Sf_Lzzn: "FALSE",
    Sf_Jr_Xf: "FALSE",
    Sf_Ga_Jw: "FALSE",
    Is_Slow_Examination: "FALSE",
    Zzmm: "",
    Csrq: null,
    Byxxdm: "",
    Wyyzdm: "",
    Mzyydj: "",
    Bylbdm: "",
    Yzbm: "",
    Lxr: "",
    Bz1: "",
    Bz2: "",
    Bz3: ""
}

//渲染数据的数据模型
export const initFormTitle ={
    Test_Number: "",
    Current_Address_Detail: "",
    Examinee_Type_Code: "",
    Body_Exam_Number: "",
    Name: "",
    Sex: "",
    Grade_Id: "",
    Class_Id: "",
    Id_Number: "",
    Student_Status: "",
    Nation_Code: "",
    Phone: "",
    Current_Address: "",
    Headmaster_Name: "",
    Headmaster_Phone: "",
    Is_Unsuitable_Exercise: "",
    Is_Apply_Exempt_Examination: false,
    Sf_Ssmz: false,
    Sf_Gq_Hqzn: false,
    Sf_Twj: false,
    Sf_Lzzn: false,
    Sf_Jr_Xf: false,
    Sf_Ga_Jw: false,
    Is_Slow_Examination: false,
    Zzmm: "",
    Csrq: null,
    Byxxdm: "",
    Wyyzdm: "",
    Mzyydj: "",
    Bylbdm: "",
    Yzbm: "",
    Lxr: "",
    Bz1: "",
    Bz2: "",
    Bz3: ""
  };
